FROM node:18-alpine

WORKDIR /usr/src/app


COPY package*.json ./


RUN npm install


COPY . .


RUN ls -R /usr/src/app/src


RUN npm run build


EXPOSE 3000


CMD ["npm", "run", "start:prod"]