name: CI/CD Pipeline

on:
  push:
    branches:
      - F/facture

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd backend
          npm ci

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List backend files
        run: |
          ls -R ./backend

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t yassirrachad/factura:latest ./backend

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push yassirrachad/factura:latest

  
   