name: pipeline

on:
  push:
    branches: ['F/facture']
  pull_request:
    branches: ['F/facture']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push backend image
        run: |
          docker build -t yassirrachad/factura:latest ./backend
          docker push yassirrachad/factura:latest

      - name: Build and push frontend image
        run: |
          docker build -t yassirrachad/facturafront:latest ./frontend
          docker push yassirrachad/facturafront:latest
